name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6
      - uses: caffeinelabs/setup-mops@v1

      - name: make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: Run mops test
        run: mops test

      - name: Make sure pocket-ic is installed
        run: mops toolchain bin pocket-ic

      - name: Make sure wasm-opt is installed
        run: mops toolchain bin wasm-opt

      - name: Run mops bench
        run: mops bench

  fmt:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: latest
      - name: Prettier Check
        run: |
          npm install prettier prettier-plugin-motoko --no-save
          npx -y prettier --plugin prettier-plugin-motoko --check '**/*.{mo,json,md}'
