name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

env:
  dfx_version: 0.19.0

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: ZenVoich/setup-mops@v1.2.0

      - name: make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: Run mops test
        run: mops test

      - uses: dfinity/setup-dfx@main

      - name: Run mops bench
        run: mops bench
